"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""                                  Supertab                                  "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabDefaultCompletionType = "<Right>"
